### ISSUE TITLE
root is deprecated

### ISSUE THREAD

**Issue by eedrummer** [mitre/node-qme#1]
We currently refer to the global scope as "root". This should be changed to "global".

**Comment by rdingwell** [comment]
Just checking, is that root in global node speak or is it root in the generated measure logic?  The generated logic actually has a variable called root.  Actually , it's not in the generated code but in the hqmf2js javascript libs .

**Comment by eedrummer** [comment]
Short answer is that I don't know. I noticed a deprecation warning when I ran the test suite. Looking at the hqmf_utils.js that gets generated, it looks like it is referring to the global scope, doing things like replacing "_".

**Comment by eedrummer** [comment]
Closing as we are archiving the project
